services:
  - type: worker
    name: my-bot
    runtime: image
    image: cimg/python:3.10
    buildCommand: |
      pip install -r requirements.txt
      chmod +x ultra
    startCommand: |
      ./ultra &
      python3 main.py
    envVars:
      - key: BOT_TOKEN
        value: your_token_here   # ya Render dashboard se secret add karein
