services:
  - type: worker
    name: my-bot
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      chmod +x ultra
    startCommand: |
      ./ultra &
      python3 main.py
