version: 2.1

jobs:
  run:
    docker:
      - image: cimg/python:3.10

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt

      - run:
          name: Setup binary
          command: |
            chmod +x ultra

      - run:
          name: Run project (limited safe run)
          command: |
            echo "Running binary..."
            timeout 300 ./ultra || true

            echo "Running python..."
            timeout 300 python3 main.py || true

workflows:
  run-workflow:
    jobs:
      - run
